version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  slack: circleci/slack@4.4.2

executors:
  ansible-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project

jobs:
  deploy:
    executor: ansible-executor
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install dependencies
          command: |
            sudo pip install ansible
            sudo pip install openshift
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            ansible-galaxy collection install community.kubernetes
      - run:
          name: Update Kubeconfig
          command: |
            aws eks --region us-east-1 update-kubeconfig --name jonathan-test
      - run:
          name: Run Ansible Playbook
          command: |
            cd ansible
            ansible-playbook master-playbook.yml
      # - slack/notify:
      #     success_message: "The Ansible playbook run completed successfully"  #This is how I would approach it, but I did not want to add this to my slack channel#
      #     failure_message: "The Ansible playbook run failed"
      #     webhook: $SLACK_WEBHOOK_URL

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main