---
- name: Create Redis Horizontal Pod Autoscaler
  hosts: localhost
  tasks:
    - name: Apply HPA to Redis
      k8s:
        namespace: unqork-namespace
        definition:
          apiVersion: autoscaling/v1
          kind: HorizontalPodAutoscaler
          metadata:
            name: redis-hpa
          spec:
            scaleTargetRef:
              apiVersion: apps/v1
              kind: StatefulSet
              name: redis
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 50