---
- name: Create Secret
  hosts: localhost
  tasks:
    - name: Create a new Secret
      k8s:
        namespace: unqork-namespace
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: unqork-secret
          stringData:
            api-key: "Fake-API-Key" 